<?php
namespace console\controllers\Cs\email;


use yii\console\Controller;
use swoole_server;
use Yii;

class SwooleEmailController extends Controller
{
    private $_serv;
    private $_run;

    /**
     * 初始化
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->mainAction();
    }

    /**
     * 开启swoole
     */
    public function mainAction()
    {
        $this->_serv = new swoole_server("127.0.0.1", 9501);
        $this->_serv->set([
            'worker_num' => 2,
            'daemonize' => false,
            'log_file' => Yii::$app->basePath . '/runtime/logs/server.log',
            'task_worker_num' => 2,
            'max_request' => 5000,
            'task_max_request' => 5000,
            'open_eof_check' => true, //打开EOF检测
            'package_eof' => "\r\n", //设置EOF
            'open_eof_split' => true, // 自动分包
        ]);
        $this->_serv->on('Connect', [$this, 'onConnect']);
        $this->_serv->on('Receive', [$this, 'onReceive']);
        $this->_serv->on('WorkerStart', [$this, 'onWorkerStart']);
        $this->_serv->on('Task', [$this, 'onTask']);
        $this->_serv->on('Finish', [$this, 'onFinish']);
        $this->_serv->on('Close', [$this, 'onClose']);
        $this->_serv->start();

    }

    /**
     * @param $serv
     * @param $fd
     * @param $fromId
     */
    public function onConnect($serv, $fd, $fromId)
    {

    }

    /**
     * @param $serv
     * @param $workerId
     */
    public function onWorkerStart($serv, $workerId)
    {
        $this->_run = new Email();
    }

    /**
     * @param $serv
     * @param $fd
     * @param $fromId
     * @param $data
     */
    public function onReceive($serv, $fd, $fromId, $data)
    {
        $data = $this->unpack($data);
        $this->_run->receive($serv, $fd, $fromId, $data);
        // 投递一个任务到task进程中
        $serv->task(array_merge($data , ['fd' => $fd]));
    }

    /**
     * @param $serv
     * @param $taskId
     * @param $fromId
     * @param $data
     */
    public function onTask($serv, $taskId, $fromId, $data)
    {
        $this->_run->task($serv, $taskId, $fromId, $data);
    }

    /**
     * @param $serv
     * @param $taskId
     * @param $data
     */
    public function onFinish($serv, $taskId, $data)
    {
        $this->_run->finish($serv, $taskId, $data);
    }

    /**
     * @param $serv
     * @param $fd
     * @param $fromId
     */
    public function onClose($serv, $fd, $fromId)
    {
        echo "Client close." . PHP_EOL;
    }

    /**
     * 对数据包单独处理，数据包经过`json_decode`处理之后，只能是数组
     * @param $data
     * @return bool|mixed
     */
    public function unpack($data)
    {
        $data = str_replace("\r\n", '', $data);
        if (!$data) {
            return false;
        }
        $data = json_decode($data, true);
        if (!$data || !is_array($data)) {
            return false;
        }
        return $data;
    }
}