<?php

namespace console\controllers\Cs\Swoole;

use yii\console\Controller;
use swoole_mysql;
use Exception;
use Yii;

class MysqlController extends Controller
{
    public $db;

    public $dbConfig;

    public function init()
    {
        $this->db = new swoole_mysql;
        $this->dbConfig = [
            'host' => '127.0.0.1',
            'port' => '3306',
            'user' => 'root',
            'password' => 'root',
            'database' => 'ceshi',
            'charset' => 'utf8',
        ];

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $db = $this->db;
        $db->connect($this->dbConfig, function ($db, $r) {
            if (!$r) {
                throw new Exception('连接数据库失败');
            }
            $sql = "select * from shops where shop_id = 253";
            $db->query($sql, function($db, $result){
                dd($result);
            });
        });
    }

    public function update()
    {

    }

    public function add()
    {

    }

    public function execute($id, $username)
    {
        return true;
    }
}