<?php

namespace console\controllers\Cs\Swoole;

use yii\console\Controller;
use swoole_redis;
use Exception;
use Yii;

class RedisController extends Controller
{
    public $redis;

    public function init()
    {
        $this->redis = new swoole_redis;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $redis = $this->redis;
        $redis->connect('127.0.0.1', 6379, function(swoole_redis $redisClient, $result) {
//            echo "connect".PHP_EOL;
//            var_dump($result);

            // 同步 redis (new Redis())->set('key',2);
            /*$redisClient->set('singwa_1', time(), function(swoole_redis $redisClient, $result) {
                var_dump($result);
            });*/

            /*$redisClient->get('singwa_1', function(swoole_redis $redisClient, $result) {
                var_dump($result);
                $redisClient->close();
            });*/
//            $redisClient->keys('*gw*', function(swoole_redis $redisClient, $result) {
//                var_dump($result);
//                $redisClient->close();
//            });

        });
    }

    public function update()
    {

    }

    public function add()
    {

    }

    public function execute($id, $username)
    {
        return true;
    }
}