<?php
/**
 * Created by PhpStorm.
 * User: mac
 * Date: 2018/8/14
 * Time: 下午4:47
 */

namespace console\controllers\pattern\responsibility;

use yii\console\Controller;

/**
 * Class CsController
 * @package console\controllers\pattern\responsibility
 */
class CsController extends Controller
{
    /**
     * @var Handler
     */
    private $chain;

    public function init()
    {
        $this->chain = new FastStorage(array('bar' => 'baz'));
        $this->chain->append(new SlowStorage(array('bar' => 'baz', 'foo' => 'bar')));

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionTest1()
    {
        $request = new Request();
        $request->verb = 'get';

        dump($this->chain);

        $request->key = 'bar';
        $ret = $this->chain->handle($request);
        dump($ret);
        $request->key = 'foo';
        $ret = $this->chain->handle($request);
        dump($ret);
    }
}