<?php
namespace console\controllers\Cs\test;

use yii\base\Module;
use yii\console\Controller;

class ArgController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        echo 'Help:' . PHP_EOL;
        echo 'PHP函数参数测试' . PHP_EOL . PHP_EOL;

        echo 'Usage:' . PHP_EOL;
        echo './yii Cs/test/arg/test [action]' . PHP_EOL . PHP_EOL;

        echo 'Actions:' . PHP_EOL;

        echo 'more        不定参数测试' . PHP_EOL;
        echo 'Test    传入函数测试' . PHP_EOL;
    }

    /**
     * @desc 传入函数测试
     */
    public function actionTest()
    {
        function test($func)
        {
            if (is_callable($func)) {
                $func();
            } else {
                dump('传入的参数不能被执行！');
            }
        }

        test(function () {
            dump('执行函数');
        });
        test('demo');
        $func = function () {
            dump('执行函数2');
        };
        test($func);
    }

    /**
     * @desc   不定参数测试
     */
    public function actionMore()
    {
        function test(...$args)
        {
            dump($args);
        }

        function test2()
        {
            $args = func_get_args();
            dump($args);
        }

        test(1, 2, 3, 4, [1, 2, 3]);
        test2(1, 2, 3, 4, [1, 2, 3]);
    }


}