<?php
namespace console\controllers\Cs\test;

use yii\console\Controller;
use yii\helpers\ArrayHelper;

class DateController extends Controller
{
    /**
     * 初始化
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        echo 'Help:' . PHP_EOL;
        echo 'date函数参数测试' . PHP_EOL;

        echo 'Usage:' . PHP_EOL;
        echo './yii Cs/test/date [action]' . PHP_EOL;

        echo 'Actions:' . PHP_EOL;

        echo 'format              format测试' . PHP_EOL;
        echo 'week                第几年的第几周' . PHP_EOL;
    }

    /**
     * format测试
     */
    public function actionFormat()
    {
        $week = date("W");
        $msg = sprintf("今天是一年的第%d周", $week);
        dump($msg);
        $time = time();
        for ($i = 0; $i < 20; $i++) {
            $time = strtotime("-1 weeks", $time);
            $week = date("W", $time);
            $msg = sprintf("上一周是第%d周", $week);
            dump($msg);
        }
    }

    /**
     * 第几年的第几周
     */
    public function actionWeek()
    {
        $today = date("Y-m-d");
        dump("今天：" . $today);
        $tomorrow = date("Y-m-d", strtotime("+1 days", strtotime($today)));
        dump("明天：" . $tomorrow);
        $t2 = date("Y-m-d", strtotime("+1 days", strtotime($tomorrow)));
        dump("后天：" . $t2);
    }


}