<?php
namespace console\controllers\Cs\test;

use yii\console\Controller;
use yii\helpers\ArrayHelper;
use Yii;

class EncryptController extends Controller
{
    /**
     * 初始化
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        echo 'Help:' . PHP_EOL;
        echo 'PHP加密测试' . PHP_EOL;

        echo 'Usage:' . PHP_EOL;
        echo './yii Cs/test/encrypt [action]' . PHP_EOL;

        echo 'Actions:' . PHP_EOL;

        echo 'rsa           RSA加密测试' . PHP_EOL;
    }

    public function actionRsa()
    {
        $path = Yii::$app->basePath;
        $file = $path . '/data/rsa/test/helloworld.php';
        $this->encrypt($file);
        $file = $path . '/data/rsa/test/encrypted.php';
        $this->decrypt($file);
        dump($path);
    }

    /**
     * @param $file
     */
    private function encrypt($file)
    {
        $path = Yii::$app->basePath;
        $private_key = file_get_contents($path . '/data/rsa/rsa_private_key.pem');

        $msg = file_get_contents($file);
        $msg = base64_encode($msg);
        $len = strlen($msg);
        $step = 110;
        $result = [];
        for ($i = 0; $i < $len;) {
            $input = substr($msg, $i, $step);
            $private_key = openssl_pkey_get_private($private_key);
            // 私钥加密
            $ret = openssl_private_encrypt($input, $encrypted, $private_key);

            if (!$ret || empty($encrypted)) {
                echo "fail to encrypt file md5";
                return;
            }
            // 存储加密文件
            $encrypted = base64_encode($encrypted);
            $result[] = $encrypted;
            $i += $step;
        }
        file_put_contents($path . '/data/rsa/test/encrypted.php', json_encode($result));
    }

    /**
     * @param $file
     */
    private function decrypt($file)
    {
        $path = Yii::$app->basePath;
        $public_key = file_get_contents($path . '/data/rsa/rsa_public_key.pem');
        $msg = file_get_contents($file);
        $msg = json_decode($msg);
        $result = '';
        foreach ($msg as $item) {
            // 公钥解密
            openssl_public_decrypt(base64_decode($item), $decrypted, $public_key);
            $result .= $decrypted;
        }
        $result = base64_decode($result);
        // 存储解密文件
        file_put_contents($path . '/data/rsa/test/decrypted.php', $result);
    }
}