<?php
namespace console\controllers\Cs\test;

use common\src\app\support\models\MessageMongo;
use yii\console\Controller;
use yii\helpers\ArrayHelper;
use Yii;

class MongoController extends Controller
{
    /**
     * 初始化
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        echo 'Help:' . PHP_EOL;
        echo 'PHP函数测试' . PHP_EOL;

        echo 'Usage:' . PHP_EOL;
        echo './yii Cs/test/mongo [action]' . PHP_EOL;

        echo 'Actions:' . PHP_EOL;

        echo 'insert            新建记录' . PHP_EOL;
        echo 'query             查询' . PHP_EOL;
        echo 'count             聚合使用（统计7天之前用户访问个数）' . PHP_EOL;
        echo 'del               删除测试' . PHP_EOL;
        echo 'update            修改测试' . PHP_EOL;
    }

    /**
     * 修改测试
     * @param $id
     */
    public function actionUpdate($id)
    {
        $model = MessageMongo::find()->where(['_id'=>$id])->one();
        if ($model){
            $model->name = '小林';
            dd($model->save());
        }
    }

    /**
     * 删除测试
     * @param $id
     */
    public function actionDel($id)
    {
        $model = MessageMongo::find()->where(['_id' => $id])->one();
        $model->delete();
    }

    /**
     * 聚合使用(统计7天之前用户访问个数)
     */
    public function actionCount()
    {
        $log_counts = [];
        $today = mktime(0, 0, 0, date('n'), date('j'), date('Y'));
        $sectionData = [];
        $user_count_log = [];
        for ($i = 6; $i >= 0; $i--) {
            $targetTime = $today - ($i * 3600 * 24);
            $sectionData[] = date('m-d', $targetTime);
            $query = MessageMongo::find();
            $ops = array(
                array('$match' => array('name' => 'xiaolin')),
                array('$match' => array('>=', 'time', $targetTime)),
                array('$match' => array('<', 'time', ($targetTime + 3600 * 24))),
            );
            //统计类型
            if (!empty($type)) {
                $ops[] = array('$match' => array('type' => $type));
            }
            $ops[] = array('$group' => array("_id" => '$user_id', 'count' => ['$sum' => 1]));
            $count = $query
                ->getCollection()->aggregate($ops);
            $user_count_log[] = count($count);
        }
        $log_counts = [
            $sectionData,
            $user_count_log,
        ];
        dd($log_counts);
    }

    /**
     * 查询测试
     */
    public function actionQuery()
    {
        $query = MessageMongo::find()->where(['name' => 'xiaolin']);
        $model = $query->asArray()->all();
        dd($model);
    }

    /**
     * 新建记录
     */
    public function actionInsert()
    {
        $model = new MessageMongo();
        $model->name = 'xiaolin';
        $model->title = '测试';
        $model->content = '内容测试';
        $model->time = time();
        dd($model->save());

    }
}