<?php
namespace console\controllers\Cs\test;

use yii\console\Controller;
use yii\helpers\ArrayHelper;
use Yii;

class PasswordController extends Controller
{
    /**
     * 初始化
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        echo 'Help:' . PHP_EOL;
        echo 'Password Hashing函数测试' . PHP_EOL;

        echo 'Usage:' . PHP_EOL;
        echo './yii Cs/test/password [action]' . PHP_EOL;

        echo 'Actions:' . PHP_EOL;

        echo 'check               密码测试' . PHP_EOL;
    }

    /**
     * 密码验证
     */
    public function actionCheck()
    {
        $pwd = '910123';
        dump("密码是{$pwd}");
        $hash = password_hash($pwd, PASSWORD_DEFAULT);
        dump("加密后" . $hash);
        if (password_verify($pwd, $hash)) {
            dump('密码验证成功！');
        } else {
            dump('密码验证错误！');
        }
    }
}