<?php
namespace console\controllers\Cs\test;

use yii\console\Controller;
use yii\helpers\ArrayHelper;
use Yii;

/**
 * Created by PhpStorm.
 * User: mac
 * Date: 2018/1/26
 * Time: 下午3:19
 */
class PcreController extends Controller
{
    /**
     * 初始化
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        echo 'Help:' . PHP_EOL;
        echo 'PCRE函数参数测试' . PHP_EOL;

        echo 'Usage:' . PHP_EOL;
        echo './yii Cs/test/pcre [action]' . PHP_EOL;

        echo 'Actions:' . PHP_EOL;

        echo 'match             正则匹配' . PHP_EOL;
        echo 'quote             转移正则表达式' . PHP_EOL;
        echo 'replace           执行一个正则表达式的搜索和替换' . PHP_EOL;
    }

    /**
     * 执行一个正则表达式的搜索和替换
     */
    public function actionReplace()
    {
        $str = "http://www.missxiaolin.com/v1/user/info";
        $preg = "/^(http)(.*\/)(\w+)$/";
        dump('原先字符串：' . $str);
        $newStr = preg_replace($preg, 'https${2}${3}/test', $str);
        dump('正则转换后：' . $newStr);
    }

    /**
     * 转移正则表达式
     */
    public function actionQuote()
    {
        $str = "http://sss\nfz$";
        dump('原字符串:' . $str);
        $newStr = preg_quote($str, '/');
        dump('转义后:' . $newStr);
    }

    /**
     * 正则匹配
     */
    public function actionMatch()
    {
        $str = "com.peppertv.rmb6";
        dump('原先字符串:' . $str);
        preg_match("/rmb[0-9]+$/", $str, $rmb);
        dump('结构:' . $rmb[0]);
    }
}