<?php
namespace console\controllers\Cs\test;

use common\src\app\support\models\ShopsModel;
use yii\console\Controller;
use yii\helpers\ArrayHelper;
use Yii;

class XsController extends Controller
{
    /**
     * 初始化
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        define('XS_APP_ROOT', Yii::$app->basePath . '/data/xunsearch/');
        echo 'Help:' . PHP_EOL;
        echo '开源搜索引擎测试' . PHP_EOL;

        echo 'Usage:' . PHP_EOL;
        echo './yii Cs/test/xs [action]' . PHP_EOL;

        echo 'Actions:' . PHP_EOL;

        echo 'xsAdd             讯搜添加文档' . PHP_EOL;
        echo 'xsQuery           讯搜搜索文档' . PHP_EOL;
    }

    public function actionXsAdd()
    {
        try {
            $xs = new \XS('demo'); // 建立 XS 对象，项目名称为：demo
            $index = $xs->index; // 获取 索引对象

            // 执行清空操作
            // $index->clean();
            $index->beginRebuild();

            $model = ShopsModel::find()->where(['shop_id' => 253])->one();

            $data = $model->toArray();

            $doc = new \XSDocument;
            $doc->setFields($data);

            // 添加到索引数据库中
            // $index->add($doc);
            $index->update($doc);
            $index->endRebuild();

        } catch (\Exception $e) {
            dd($e->getMessage());
        }

    }

    public function actionXsQuery()
    {
        $xs = new \XS('demo'); // 建立 XS 对象，项目名称为：demo
        $search = $xs->search; // 获取 搜索对象

        $query = '超级'; // 这里的搜索语句很简单，就一个短语

        $search->setQuery($query); // 设置搜索语句
        // $search->addWeight('subject', 'xunsearch'); // 增加附加条件：提升标题中包含 'xunsearch' 的记录的权重
        // $search->setLimit(5, 0); // 设置返回结果最多为 5 条，并跳过前 10 条

        $docs = $search->search(); // 执行搜索，将搜索结果文档保存在 $docs 数组中
        $count = $search->count(); // 获取搜索结果的匹配总数估算值
        dump($docs);
        dump('共搜索到' . $count . '个文档');
    }

}