<?php
namespace console\controllers\Test;


use common\components\Email;
use yii\console\Controller;
use swoole_server;
use Yii;

class SwooleEmailController extends Controller
{
    private $_serv;
    private $_run;

    /**
     * 初始化
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->mainAction();
    }

    /**
     * 开启swoole
     */
    public function mainAction()
    {


    }


}