<?php
namespace console\controllers\districts;

use common\components\Train;
use common\src\app\support\service\DistrictService;
use yii\console\Controller;
use Yii;

class CsController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        echo 'Help:' . PHP_EOL;

        echo 'Actions:' . PHP_EOL;
        echo 'test                  添加训练数据' . PHP_EOL;
        echo 'train                 训练' . PHP_EOL;
    }

    public function actionTest()
    {
        DistrictService::getInstance()->crawl();
    }

    public function actionTrain()
    {
        dump(Train::getInstance()->predict([39.9223757639, 116.4221191406]));
    }
}