<?php
/**
 * Created by PhpStorm.
 * User: mac
 * Date: 2018/8/13
 * Time: 下午3:40
 */

namespace console\controllers\pattern\decorator;


use yii\console\Controller;

class CsController extends Controller
{
    /**
     * @var Webservice
     */
    private $service;


    public function init()
    {
        $this->service = new Webservice("foobar");
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 测试 JSON 装饰者。
     * 这里的 assertEquals 是为了判断返回的结果是否符合预期。
     */
    public function actionTest1()
    {
        $service = new JsonRenderer($this->service);

        // foobar
        dump($service->renderData());
    }

    public function actionTest2()
    {
        $service = new XmlRenderer($this->service);
        /*        '<?xml version="1.0"?><content>foobar</content>'*/
        dump($service->renderData());
    }
}